name: Run Auto Daily Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '41 18 * * 1-5' # 10:41 AM PST (18:41 UTC) on weekdays
    - cron: '50 18 * * 1-5' # 10:50 AM PST (18:50 UTC) on weekdays
    - cron: '52 18 * * 1-5' # 10:52 AM PST (18:52 UTC) on weekdays
    - cron: '54 18 * * 1-5' # 10:54 AM PST (18:54 UTC) on weekdays
jobs:
  run-bash:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Run Auto Daily script
      env:
        CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        SHEET_ID: ${{ secrets.SHEET_ID }}
        WEEKLY_WEBHOOK_URL: ${{ secrets.WEEKLY_WEBHOOK_URL }}
        DAILY_WEBHOOK_URL: ${{ secrets.DAILY_WEBHOOK_URL }}
        RANGE: ${{ secrets.RANGE }}
      run: |
        chmod +x ./autodaily.sh
        ./autodaily.sh
