name: Run Bash Script

on:
  push:
    branches:
      - main

jobs:
  run-bash:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Bash script
      run: |
        chmod +x scripts/myscript.sh
        ./scripts/myscript.sh
