name: Run Empty Txts

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 21 * * 5' # At 09:'0 PM, only on Friday

permissions:
  contents: write

jobs:
  run-bash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Empty Txts
        env:
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          WEEKLY_WEBHOOK_URL: ${{ secrets.WEEKLY_WEBHOOK_URL }}
          DAILY_WEBHOOK_URL: ${{ secrets.DAILY_WEBHOOK_URL }}
          RANGE: ${{ secrets.RANGE }}
        run: |
          chmod +x ./autodel.sh
          ./autodel.sh

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add data.txt
          git commit -m "Emptied data.txt" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
